sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: lccQ5GfRz4BlRXnqzcVL3kYsva7MYbhYWqxSBCLHyR7Cg8lGmtDTg2oakY7TssSUMMhzjBrqg1IdF51cffxlVeDADmxUtHEJzmkLvNNP8NApVCfJGMKqcX+IZUC3BmqZwccM7rHFr/w6qWf/0DsoXrpiwlt2YxqKKPku7eY+zMwicrP+u2T6GeUC9w/4XWixsPBZDgUKio3+vGredPZPbyQUIlZwFvyxWnhWbKzwXzsYctGZJJ6NcGG08482lkcAJ8C6S7+9re0eR1hRQuTEjcD26U2JD5/2f17rfYzX9s0yScoioW0mmSIn1d4C7Rj8SMuJI1kp1+9i3BOHjVphbgikTwtuLktJr9XASV53VV0wzWOGh6Zk8BeRM7OZBnOsxLzdrwjc1EpeC4W8fCp2fz8qVzlEA+6jV4lsx1Yo1F/ImlXRZ6D8SQgWdZkHWN63Vkf4+eUIRCofMHXkeP/CFXCUjvg15vhSFAIXgANjgkz4OJ6yaT3Q5SdakwSU7ANiy3LmQ2QuFG0L4T304jvAYLwD5P3Vynz7OJZRzcJRREjWjGzAGWOCndSuEp4vI1IRN2JbSvpmtNdLRiqhTS4fi1mVO7Ae8nm0KuagFQ/gKu4oFVislitSuLYY2o8z9Txa8mfcNaiFaeFK2gb0f4j4S1OWsUyTppqBZipM+Rd7bbI=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: PlXkDhupCJJOxOT5Ee9BKbvD28q3eHCZJ3RXyDzysvQqEmjvM88ebmQqHh7YTRDqtASI68M3f1lyyc2Q5jseDfsDpQ1Ad/NNsrXQ1+m2Lv7dQ5pYVsGd9FGAJ/RcFe9f28zx3bNg3+CE39HtxDFc9//4UltP/1Ny3WvgMGCL5bw2bhuK8b0CUCsIrnafnFBIp49uTsKrxR3oCX62jrwV5wHGjr7NZHspMhLegiVors7cqRPvUPxv5NO3bnYaTYeQ0tKtvzFgLgr7rVQOkhNCkuWJR08pbyF8thI2kmzUYPk9IlF9olzi0feXMW8g9tAQkWf21KlVlyYlgCKB//+wu7xXRXiVOLQiIcFxXtFZKKlOUFr1Hsa5Zyc/7DE/WjYVISMf/2a+9C123/sz+WXktCzuZGbsKJSTYg7QSUYBlJlQQmksNe+kLboM8YdPRUGrilt9s4lEHoZnBBIFkk7s176aZGjpbfGIeLzOqfzRp4jtf8S4HCWaccQKoJTrROaIi6VLJ7oYiziJIO6PK6SRBcMX2u8PiPkbAXysUhmEEDwvrxGYvcNp2UdwRMXP4E074jdnFSPe9OrDOZEM3dTUltvSibzqaU0Dw0r45zfh+co5le2SjRX6XCTeQs8LTyuMq2rIGoTE5SMw5Dr5MLCMndcjsLoSjwAPp4YoCxfwY4Y=
